### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007
  description: Microsoft Intelligent Application Gateway 2007 følger politikken for fast livscyklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: c3c1ca3898de2c0ac61b79395f1c75e4689d91980dbeb4f5641b05160088230d
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: da-DK
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2495139"
name: Microsoft Intelligent Application Gateway 2007
summary: "Microsoft Intelligent Application Gateway 2007 følger politikken for [Fast](/lifecycle/policies/fixed) livscyklus. \n\n\n> [!IMPORTANT]\n> Understøttelse af dette produkt er ophørt Se vejledningen til migrering nedenfor.\n"
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 06/01/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Service Pack 2
  startDate: 11/27/2008
  endDate: 07/11/2017
- version: Service Pack 1
  startDate: 09/03/2007
  endDate: 01/12/2010
- version: Original Release
  startDate: 06/01/2007
  endDate: 10/14/2008
content: "\n## <a name=\"links\"></a>Links \n* [Microsoft Intelligent Application Gateway 2007 Roadmap](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Politik for servicepakker](/lifecycle/policies/fixed#service-packs)"
