### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.5 til Windows-skriveborde
  description: Microsoft Application Virtualization Hosting 4.5 til Windows Desktop følger politikken for fast livscyklus.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 2e50dff8c1e7f1db82d46a06704bad1c76d16598
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: da-DK
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4154028"
name: Microsoft Application Virtualization Hosting 4.5 til Windows-skriveborde
summary: >
  Microsoft Application Virtualization Hosting 4.5 til Windows Desktop følger politikken for den [Faste](/lifecycle/policies/fixed) livscyklus.


  Dette gælder for de følgende versioner: Windows Desktops


  > [!IMPORTANT]

  > Understøttelse af dette produkt er ophørt Se oplysninger om overførsel nedenfor.
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Links \n* [Information om produkter og migrering](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Politik for servicepakker](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Versioner \n* For Windows Desktops"
