### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.5
  description: Microsoft Application Virtualization 4.5 følger politikken for fast livscyklus.
  ms.date: 09/01/2020
  keywords: for Terminal Services,for Windows Desktops
  ms.openlocfilehash: d70bed6b9c9e05d19efb27509f15e13fb8bf5735
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: da-DK
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4108296"
name: Microsoft Application Virtualization 4.5
summary: >
  Microsoft Application Virtualization 4.5 følger politikken for [Fast](/lifecycle/policies/fixed) livscyklus.


  Dette gælder for følgende udgaver: Terminal Services, Windows Desktop


  > [!IMPORTANT]

  > Understøttelse af dette produkt er ophørt Se vejledningen til migrering nedenfor.
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Links \n* [Vejledning om migrering](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Politik for servicepakker](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Da App-V 4.6-klienten anvender App-V 4.5-serveren, understøttes App-V 4.5-serveren fortsat i henhold til livscyklusdatoerne for App-V 4.6, når den bruges sammen med den understøttede App-V 4.6-klient.\n\n## <a name=\"editions\"></a>Versioner \n* til Terminal Services\n* For Windows Desktops"
