### YamlMime:Lifecycle
metadata:
  title: Konfigurationsstyring til Microsoft System Center 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 følger politikken for fast livscyklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: da-DK
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "851573"
name: Konfigurationsstyring til Microsoft System Center 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 følger [politikken](/lifecycle/policies/fixed) for fast livscyklus.



  > [!IMPORTANT]

  > Supporten til dette produkt er ophørt. Se vejledningen til migrering nedenfor.
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Links \n* [Vejledning i migration](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Yderligere vejledning i migrering](/mem/configmgr/core/migration/planning-for-migration)"
