### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security følger den faste livscykluspolitik.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: da-DK
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908680"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security følger den [faste](/lifecycle/policies/fixed) livscykluspolitik.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Links \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security er blevet udgået. Support er en afslutning af juli 14th, 2015. Opdateringer til antimalware-og antispywaredefinitioner vil ikke længere være tilgængelige efter udløbet af support til produktversionen. Evaluer System Center Endpoint Protection som erstatning."
