### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security følger den faste livscykluspolitik.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: da-DK
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924249"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security følger den [faste](/lifecycle/policies/fixed) livscykluspolitik.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Links \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security er blevet udgået fra og med Juli 14th, 2015. Opdateringer til antimalware-og antispywaredefinitioner vil ikke længere være tilgængelige efter udløbet af support til produktversionen. Evaluer System Center Endpoint Protection som erstatning."
