### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 til Windows-skriveborde
  description: Microsoft Application Virtualization Hosting 5.1 til Windows Desktop følger politikken for den faste livscyklus.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 til Windows-skriveborde
summary: |+
  Microsoft Application Virtualization Hosting 5.1 til Windows Desktop følger politikken for den [faste](/lifecycle/policies/fixed) livscyklus.

  Dette gælder for de følgende versioner: Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Links 
  * [Produktinformation](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Versioner 
  * For Windows Desktops