### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security følger politikken for fast livscyklus.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security følger politikken for den [faste](/lifecycle/policies/fixed) livscyklus.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Links 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security er blevet afbrudt pr. 14. juli 2015. Antimalware- og Antispyware-definitionsopdateringer vil ikke længere være tilgængelige efter afslutningen af supporten til produktversionen. Vurder System Center Endpoint Protection som en erstatning.