### YamlMime:Lifecycle
metadata:
  title: SoftGrid-programvirtualisering
  description: SoftGrid-programvirtualisering følger politikken for fast livscyklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: da-DK
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "810526"
name: SoftGrid-programvirtualisering
summary: >
  SoftGrid-programvirtualisering følger [politikken](/lifecycle/policies/fixed) for fast livscyklus.


  Dette gælder for følgende udgaver: 4.1 til stationære pc'er, 4.2 til stationære pc'er, til Terminal Services 4.1


  > [!IMPORTANT]

  > Supporten er ophørt. Se vejledningen til migrering nedenfor.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Links \n* [Vejledning i migration](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Udgaver \n* 4.1 til stationære pc'er\n* 4.2 til stationære pc'er\n* til Terminal Services 4.1"
